### Importing Libraries

In [64]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams['figure.figsize'] = (20,10)

### Importing Dataset

In [65]:
df1 = pd.read_csv('marks dataset.csv')
df1.head()

gender race/ethnicity parental level of education         lunch  \
0    male        group A                 high school      standard   
1  female        group D            some high school  free/reduced   
2    male        group E                some college  free/reduced   
3    male        group B                 high school      standard   
4    male        group E          associate's degree      standard   

  test preparation course  math score  reading score  writing score  
0               completed          67             67             63  
1                    none          40             59             55  
2                    none          59             60             50  
3                    none          77             78             68  
4               completed          78             73             68

In [66]:
df1.shape

(1000, 8)

### Deleting the unneccessary columns


In [67]:
df2 = df1.drop(['gender' , 'race/ethnicity' , 'parental level of education' , 'lunch'], axis='columns')
df2.shape


(1000, 4)

In [68]:
df2.head()

test preparation course  math score  reading score  writing score
0               completed          67             67             63
1                    none          40             59             55
2                    none          59             60             50
3                    none          77             78             68
4               completed          78             73             68

In [69]:
df2.isnull().sum()

test preparation course    0
math score                 0
reading score              0
writing score              0
dtype: int64

In [70]:
df2['test preparation course'].unique()

array(['completed', 'none'], dtype=object)

In [71]:
df2['math score'].unique()

array([ 67,  40,  59,  77,  78,  63,  62,  93,  47,  99,  80,  74,  81,
        69,  58,  54,  23,  39,  83,  71,  44,  46,  51,  53,  33,  87,
        65,  79,  68,  57,  98, 100,  60,  64,  52,  36,  56,  88,  42,
        76,  49,  72,  31,  32,  97,  94,  95,  45,  75,  66,  70,  82,
        92,  30,  41,  43,  55,  73,  48,  86,  84,  50,  89,  91,  85,
        61,  35,  90,  96,  13,  38,  28,  26,  37,  29,  34,  25],
      dtype=int64)

In [72]:
df2['reading score'].unique()

array([ 67,  59,  60,  78,  73,  77,  88,  56,  42,  83,  87,  74,  61,
        47,  62,  44,  32,  76,  52,  69,  55,  38,  45,  68,  89,  54,
        79,  41,  65,  81,  75,  70,  46,  63,  72,  58,  53,  57,  80,
        51,  66,  82,  93,  64,  91,  43,  71, 100,  50,  33,  34,  90,
        84,  95,  98,  92,  85,  49,  86,  48,  94,  36,  28,  39,  29,
        96,  97,  40,  27,  37,  99,  31,  35], dtype=int64)

In [73]:
df2['writing score'].unique()

array([ 63,  55,  50,  68,  76,  84,  65,  45,  85,  90,  73,  57,  42,
        44,  31,  88,  54,  32,  56,  60,  89,  51,  77,  39,  71,  74,
        75,  72,  64,  82,  70,  87,  78,  49,  47,  62,  83,  48,  59,
        97,  81,  67,  69,  61,  93, 100,  53,  79,  58,  33,  86,  66,
        46,  80,  91,  92,  95,  99,  96,  28,  52,  24,  40,  43,  94,
        23,  38,  30,  35,  41,  98,  36,  27,  26,  34,  37], dtype=int64)

### Creating total marks column

In [74]:
df3 = df2.copy()
df3['total marks'] = df3['math score'] + df3['reading score'] + df3['writing score']
df3.head()

test preparation course  math score  reading score  writing score  \
0               completed          67             67             63   
1                    none          40             59             55   
2                    none          59             60             50   
3                    none          77             78             68   
4               completed          78             73             68   

   total marks  
0          197  
1          154  
2          169  
3          223  
4          219

### Creating total percentage Column

In [75]:
df3['total percentage'] = df3['total marks']/300*100
df3.head()

test preparation course  math score  reading score  writing score  \
0               completed          67             67             63   
1                    none          40             59             55   
2                    none          59             60             50   
3                    none          77             78             68   
4               completed          78             73             68   

   total marks  total percentage  
0          197         65.666667  
1          154         51.333333  
2          169         56.333333  
3          223         74.333333  
4          219         73.000000

### Rounding off the percentage

In [76]:
df3['total percentage'] = round(df3['total percentage'], 2 )

In [77]:
df3.head()

test preparation course  math score  reading score  writing score  \
0               completed          67             67             63   
1                    none          40             59             55   
2                    none          59             60             50   
3                    none          77             78             68   
4               completed          78             73             68   

   total marks  total percentage  
0          197             65.67  
1          154             51.33  
2          169             56.33  
3          223             74.33  
4          219             73.00

### Checking for the outliers


- Marks should not less than zero


In [78]:

maths = df3['math score']
len(maths[maths<0])


0

- Marks should not greater than zero



In [79]:
len(maths[maths>100])


0

In [80]:
read = df3['reading score']
len(read[read<0])


0

In [81]:
len(read[read>100])

0

In [82]:
write = df3['writing score']
len(write[write<0])

0

In [83]:
len(write[write>100])

0

In [84]:
df3.describe()

math score  reading score  writing score  total marks  \
count  1000.000000    1000.000000    1000.000000  1000.000000   
mean     66.396000      69.002000      67.738000   203.136000   
std      15.402871      14.737272      15.600985    43.542732   
min      13.000000      27.000000      23.000000    65.000000   
25%      56.000000      60.000000      58.000000   175.750000   
50%      66.500000      70.000000      68.000000   202.000000   
75%      77.000000      79.000000      79.000000   235.000000   
max     100.000000     100.000000     100.000000   300.000000   

       total percentage  
count       1000.000000  
mean          67.712000  
std           14.514123  
min           21.670000  
25%           58.585000  
50%           67.330000  
75%           78.330000  
max          100.000000

In [85]:
df3

test preparation course  math score  reading score  writing score  \
0                 completed          67             67             63   
1                      none          40             59             55   
2                      none          59             60             50   
3                      none          77             78             68   
4                 completed          78             73             68   
..                      ...         ...            ...            ...   
995                    none          73             70             65   
996               completed          85             91             92   
997                    none          32             35             41   
998                    none          73             74             82   
999               completed          65             60             62   

     total marks  total percentage  
0            197             65.67  
1            154             51.33  
2            169             56.33  
3            223             74.33  
4            219             73.00  
..           ...               ...  
995          208             69.33  
996          268             89.33  
997          108             36.00  
998          229             76.33  
999          187             62.33  

[1000 rows x 6 columns]